global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using InfloUserManagerWebAPI.Controllers;
global using InfloUserManagerWebAPI.Data;
global using InfloUserManagerWebAPI.DTOs;
global using InfloUserManagerWebAPI.Handlers;
global using InfloUserManagerWebAPI.Interfaces;
global using InfloUserManagerWebAPI.Models;